#!/bin/bash
#Makescript v1.00
#Genzo Namikawa
#genzo.namikawa@jacks.sdstate.edu

printf "Makescript v1.00\n\n"
printf "=== Library Existance Check =========================\n\n"
printf " === [CFLAGS] [LIBRARY] gtk+-3.0 ===\n\n"
printf " $(pkg-config --cflags --libs gtk+-3.0)\n\n"
printf " === [LIBRARY] libusb ===\n\n"
printf " $(pkg-config --libs libusb-1.0)\n\n"
printf "=====================================================\n\n"
printf "Building scan-c.c\n"
gcc -o "scan-c" $(pkg-config --cflags --libs gtk+-3.0) $(pkg-config --libs libusb-1.0) -ludev -rdynamic "scan-c.c"
printf "Done.\n"
